[package]
name = "awe-wordpress-core"
version = "0.1.0"
description = "WordPress on Wasmer"

[dependencies]
"php/php-web-server" = "^0.1.2"

[fs]
"/app" = "."

[[command]]
name = "start"
module = "php/php-web-server:php-web-server"
runner = "wasi"

[command.annotations.wasi]
env = [
    "DOCUMENT_ROOT=/app",
    "SERVER_NAME=awe-wordpress-core.wasmer.app"
]
main-args = ["-S", "0.0.0.0:8080", "-t", "/app"]